name: PSR-12

on: [push]

jobs:
  phpmd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install composer and dependencies
        uses: php-actions/composer@v6

      - name: Run PHPCS
        uses: php-actions/phpcs@v1
        with:
          version: composer
          php_version: 8.4
          path: src/,tests/
          standard: phpcs.xml